spring:
  data:
    redis:
      url: redis://default:RYdFZwAkukk7NsDTk9O0c129gzst0xxc@redis-14219.c256.us-east-1-2.ec2.cloud.redislabs.com:14219
      database: 0

  datasource:
    url: jdbc:mysql://localhost/booking_system?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: Kkl@14994
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
